### ISSUE TITLE
Incorrect function name getCurrent_mV in documentation

### ISSUE THREAD

**Issue by antarestrader** [wollewald/INA226_WE#2]
In the [List of public functions.pdf](https://github.com/wollewald/INA226_WE/blob/master/List%20of%20public%20functions.pdf) the current function is called `getCurrent_mV()` and describes its output as current in mV.  The function as implemented is `getCurrent_mA()` and reads current in mA as expected.  This is a documentation error only.

**Comment by wollewald** [comment]
@antarestrader: oops! Thank you, I have changed it.
